version: '3.9'
services:
  rebase-test:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rebase-test
    ports:
      - "3230:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-storage:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

volumes:
  db-storage:
